### PR TITLE
redis_exporter: update 0.11.2->1.0.3

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by foxxx0 — APPROVED** [review]

**Comment by tkuther** [comment]
https://github.com/oliver006/redis_exporter/releases/tag/v1.0.0
> Put the released binary file into a folder inside the .tar.gz / zip files.

So the archive stuff needs some work, too.

Simply bumping the version results in
```
# ls -l /opt/redis_exporter-1.0.3.linux-amd64/redis_exporter-v1.0.3.linux-amd64/
insgesamt 8512
-rw-r--r-- 1 root root    1063 Jun 21 03:14 LICENSE
-rw-r--r-- 1 root root    9804 Jun 21 03:14 README.md
-rwxr-xr-x 1 root root 8697888 Jun 21 03:14 redis_exporter
```
which causes a dead symlink and failed service.

**Comment by bastelfreak** [comment]
@tkuther do you have an idea on how to fix this?

**Comment by tkuther** [comment]
@bastelfreak I came up with this patch in our local clone:
```
diff --git a/manifests/redis_exporter.pp b/manifests/redis_exporter.pp
index edf955f..d80bad4 100644
--- a/manifests/redis_exporter.pp
+++ b/manifests/redis_exporter.pp
@@ -129,7 +129,13 @@ class prometheus::redis_exporter (
     # redis_exporter lacks.
     # TODO: patch prometheus::daemon to support custom extract directories
     $exporter_install_method = 'none'
-    $install_dir = "/opt/${service_name}-${version}.${os}-${arch}"
+    if (versioncmp($version, '1.0.0') >= 0) {
+      $install_dir = "/opt/${service_name}-v${version}.${os}-${arch}"
+      $extract_path = '/opt'
+    } else {
+      $install_dir = "/opt/${service_name}-${version}.${os}-${arch}"
+      $extract_path = $install_dir
+    }
     file { $install_dir:
       ensure => 'directory',
       owner  => 'root',
@@ -139,7 +145,7 @@ class prometheus::redis_exporter (
     -> archive { "/tmp/${service_name}-${version}.${download_extension}":
       ensure          => present,
       extract         => true,
-      extract_path    => $install_dir,
+      extract_path    => $extract_path,
       source          => $real_download_url,
       checksum_verify => false,
       creates         => "${install_dir}/${service_name}",
```

It's a bit ugly, but works.

**Comment by bastelfreak** [comment]
@tkuther I added your diff. Can you take a look at the failing travis jobs?

**Comment by tkuther** [comment]
@bastelfreak the log doesn't show any obvious errors (other than the redis_exporter service failing)

Honestly, I have no idea what's wrong. Just tested Debian 9 and CentOS 7 in Vagrant with the latest release of puppet-prometheus + patch from this pull request.

**Comment by alexjfisher** [comment]
I fixed the redis exporter in https://github.com/voxpupuli/puppet-prometheus/pull/387

Perhaps updating of the default should now wait until it can be grouped together with other breaking changes (updating the default versions of other exporters).  I'll close this for now.

**Comment by alexjfisher** [comment]
@bastelfreak Actually, as the next release is already a breaking one (dropping ubuntu 14.04), I'll create a new PR for this now.

**Pull request closed without merging**
