### PR TITLE
Support prometheus >= 2.0

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
Background: https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/#flag-changes

**Comment by bastelfreak** [comment]
Hi @sathieu, thanks for this PR. Are you able to provide tests for this?

**Comment by sathieu** [comment]
@bastelfreak No. Sorry.

**Comment by bastelfreak** [comment]
Todo for me later: We can maybe add a simple acceptance test to prove this is working

**Comment by sathieu** [comment]
PR updated with tests.

**Comment by bastelfreak** [comment]
Thanks for the unit tests @sathieu. We should probably add basic acceptance tests for this before we merge it. I will have a look later.

**Comment by bastelfreak** [comment]
I will test them in https://github.com/voxpupuli/puppet-prometheus/pull/86

**Comment by bastelfreak** [comment]
@sathieu can you rebase please? Acceptance tests are now available in our master branch.

**Comment by sathieu** [comment]
The acceptance tests are sometimes failing, but I think it's not due to this PR...

**Comment by bastelfreak** [comment]
Damn, I've no idea where the issue is. I thought I got it fixed while implementing the tests.

**Comment by sathieu** [comment]
can you restart those failing checks and see if it works?

**Comment by bastelfreak** [comment]
Restarted the failed one

**Comment by bastelfreak** [comment]
Thanks for this @sathieu!

**Pull request merged**
