### PR TITLE
ran release prep

### PR DESCRIPTION
**Pull request by canihavethisone**
#### Pull Request (PR) description
Release prep for v14.0.1 with dependency increase

### CODE REVIEW

**Comment by TheMeier** [comment]
There is still to open PRs I would like to get into v15 (https://github.com/voxpupuli/puppet-prometheus/pulls?q=is%3Aopen+is%3Apr+milestone%3Av15.0.0), and has to be a major release. Lots of breaking changes are already in.
Also I did mark a lot of issues `skip-changelog`

**Review by TheMeier — COMMENTED** [review]
There is still to open PRs I would like to get into v15 (https://github.com/voxpupuli/puppet-prometheus/pulls?q=is%3Aopen+is%3Apr+milestone%3Av15.0.0), and has to be a major release. Lots of breaking changes are already in.
Also I did mark a lot of issues `skip-changelog`

**Review by TheMeier — CHANGES_REQUESTED** [review]
needs re-create

**Comment by canihavethisone** [comment]
I'll leave it alone in that case as I'm unsure exactly what you want

**Pull request closed without merging**
