### PR TITLE
[WIP] add postgres_exporter

### PR DESCRIPTION
**Pull request by tuxmea**
postgres_exporter needs environment settings to be functional
this results in a change of the daemon service templates for launchd and
systemd.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@tuxmea on a first view this looks good, is it still WIP? Otherwise I can merge it and do a release in the afternoon.

**Comment by tuxmea** [comment]
@bastelfreak yes, this is still WIP. I still don't like the idea of having the service scripts adding content just for this exporter. Besides this: I have not yet tested whether the exporter is working correctly.

**Comment by pugnacity** [comment]
@tuxmea i would like to rollout this into production, any change that this will make it to the next release?

**Comment by tuxmea** [comment]
@pugnacity I have not yet had time for testing the postgres exporter (I am busy with running docker daemon inside docker containers). I have time for testing this at the end of this year.
Feel free to merge in case that everybody agrees that this is looking like working.

**Comment by bastelfreak** [comment]
@pugnacity can you test if this is working for you?

**Comment by pugnacity** [comment]
It currently doesn't work.
* Download URL has to been adjusted, since release v0.4.1 the url scheme has been changed for postgres_exporter
* Environment needs a carriage return otherwise ExecStart will be on the same line

**Comment by tuxmea** [comment]
@pugnacity can you please check again?

**Comment by pugnacity** [comment]
@tuxmea unfortunatly this is still not working
 ```Error: Execution of '/usr/bin/curl 
https://github.com/wrouesnel/postgres_exporter/releases/download/v0.4.1/postgres_exporter -o /tmp/postgres_exporter-0.4.1.tar.gz_20180208-28956-1kg8w42 -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found
Error: /Stage[main]/Prometheus::Postgres_exporter/Prometheus::Daemon[postgres_exporter]/Archive[/tmp/postgres_exporter-0.4.1.tar.gz]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/bin/curl https://github.com/wrouesnel/postgres_exporter/releases/download/v0.4.1/postgres_exporter -o /tmp/postgres_exporter-0.4.1.tar.gz_20180208-28956-1kg8w42 -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found ```

I'll try to fix it

**Comment by zeha** [comment]
Don't have time atm to make a proper PR, but this works for us (on top of puppet-prometheus 5.0.0): https://gist.github.com/zeha/dde64a71bf4cc2fa863ce63cfa4b1d0c

There's probably some ordering issues and extra_queries_source is not actually optional ...

**Comment by mika** [comment]
There was https://github.com/voxpupuli/puppet-prometheus/blob/master/manifests/postgres_exporter.pp added in the meanwhile, so this PR is probably no longer relevant?

**Comment by bastelfreak** [comment]
Hi.
I'm going to close this PR. We already have a postgres exporter. Please reopen and rebase this PR if you are still interested in it.

**Pull request closed without merging**
