### PR TITLE
Add rabbitmq exporter

### LINKED ISSUE #149: Add support for rabbitmq_exporter
It would be nice to be able to deploy the [rabbitmq_exporter](https://github.com/kbudde/rabbitmq_exporter).

### PR DESCRIPTION
**Pull request by costela**
This adds a `rabbitmq_exporter` class.
It also corrects a couple of remaining issues from #151, regarding proper quoting and exporting of environment variables under certain `init_style` conditions.

Fixes #149

### CODE REVIEW

**Comment by tuxmea** [comment]
Minor issue with documentation using old class name.

**Comment by costela** [comment]
@tuxmea oops, good catch! Fixed that and missing docs for `extra_env_vars` parameter.

**Comment by tuxmea** [comment]
looks good to me.

**Comment by bastelfreak** [comment]
thanks for the PR @costela !

**Pull request merged**
