### PR TITLE
180 rule files param

### LINKED ISSUE #180: $rule_files parameter not respected
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.9
- Ruby:2.3.6
- Distribution: Ubuntu 16.04
- Module version: 5.0.0

## How to reproduce (e.g Puppet code you use)
I declared in the init.pp manifest file the following code, which is pretty straightforward.

```
class { 'prometheus':
    rule_files        =>  ['/etc/prometheus/testing.rules'],
    scrape_configs    => $scrape_configs,
    extra_options     => $extra_options_real,
    localstorage      => "${data_dir}/prometheus",
    storage_retention => $retention,
  }
```

after running Puppet on the host, I couldn't see any change related to the parameter $rule_files. Furthermore, the resulting prometheus configuration has set an empty array:

## What are you seeing
I see no changes in regards of $rule_files parameters,  and looks like this parameter is not in use at all. The resulting yaml configuration shows only:

```
...
rule_files: []
...
``` 

if you read line 194-224:

```
$extra_rule_files = suffix(prefix(keys($extra_alerts), "${config_dir}/rules/"), '.rules')

  if ! empty($alerts) {
    ::prometheus::alerts { 'alert':
      alerts   => $alerts,
      location => $config_dir,
    }
    $_rule_files = concat(["${config_dir}/alert.rules"], $extra_rule_files)
  }
  else {
    $_rule_files = $extra_rule_files
  }

-> class { '::prometheus::config':
    global_config        => $global_config,
    rule_files           => $_rule_files,
    scrape_configs       => $scrape_configs,
    remote_read_configs  => $remote_read_configs,
    remote_write_configs => $remote_write_configs,
    config_template      => $config_template,
    storage_retention    => $storage_retention,
  }
```

You can notice that actually the value is calculated from $_rule_files

## What behaviour did you expect instead
We are currently using version `3.1.0` in production|staging|dev but we want to upgrade to `5.0.0`, however the first step is being able to set the rules parameter since at the moment is loading prometheus without any of our current rules, so I expect to have our rules in place, in a format such as:

```
rule_files:
- "/etc/prometheus/rules/alerts-service1/*.rules"
- "/etc/prometheus/rules/common/*.rules"
```
ps: there is another issue in regards of importing rules using that style, see  https://github.com/golang/go/issues/11862 for further information, but at the moment it works for us.

Please let me know if you need something from this side.
cheers!

### PR DESCRIPTION
**Pull request by bramblek1**
#### Pull Request (PR) description
Fixes an issue where `prometheus::rule_files` param was never used to populate configuration as it was not included when combining `extra_alerts` and `alerts` params.

#### This Pull Request (PR) fixes the following issues
Fixes #180

### CODE REVIEW

**Comment by bramblek1** [comment]
I think I have mistaken what belongs in the prometheus.yaml fixtures. Does this get expanded with defaults? I suspect not.

**Comment by bastelfreak** [comment]
@bramblek1 the fixtures represent an actual config from a running system. Puppet won't expand any variables in it.

**Comment by bramblek1** [comment]
Thanks @bastelfreak - I think I have run across a different issue.
`bundle exec rake test`  works for me locally. I see the beaker tests failing in travis-ci with

` Error: /Stage[main]/Prometheus::Config/File[prometheus.yaml]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/local/bin/promtool check-config /etc/prometheus/prometheus.yaml20180730-1400-tcodz7' returned 1: Checking /etc/prometheus/prometheus.yaml20180730-1400-tcodz7
    FAILED: "/etc/prometheus/$prometheus::{config_dir}/$prometheus::{alertfile_name}.rules" does not point to an existing file`

Since this error seems to come from promtool check , that string must be ending up in prometheus.yaml as a literal, which is what confused me previously.

This seems to be coming from the module hiera data/defaults.yaml - where prometheus::rule_files is using puppet DSL type syntax, not hiera lookup.
 
```
prometheus::rule_files:
  - "$prometheus::{config_dir}/$prometheus::{alertfile_name}.rules"
````
Since server.pp is handling the addition of alert.rules if `alerts` is non-empty , I think this default should be an empty list.

**Comment by bastelfreak** [comment]
thanks for fixing this @bramblek1 !

**Comment by kamusin** [comment]
Thank you so much @bramblek1!

**Pull request merged**
