### PR TITLE
fix notify $service_name in the alertmanager

### PR DESCRIPTION
**Pull request by thde**
#### Pull Request (PR) description
Fixes the alertmanager config file to notify the configured service.

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Review by alexjfisher — DISMISSED** [review]
This doesn’t look correct to me.
```
notify => Service[$notify_service],
```
instead ?

**Comment by alexjfisher** [comment]
My mistake. I see $notify_service is already a reference to the service resource.

**Review by alexjfisher — APPROVED** [review]
LGTM

**Comment by bastelfreak** [comment]
Thanks @thde !

**Comment by born4new** [comment]
@bastelfreak Any ideas when the newest version of the module will be released? I'm just impatient to get this fix 👍

**Comment by alexjfisher** [comment]
@born4new I see no reason not to roll a new release. https://github.com/voxpupuli/puppet-prometheus/pull/230

**Pull request merged**
