### PR TITLE
fix path to alert_manager binary

### PR DESCRIPTION
**Pull request by dmndru**
This patch fixes path to alert_manager binary

### CODE REVIEW

**Comment by brutus333** [comment]
It was fixed with pattdowney's PR

**Comment by dmndru** [comment]
No, it was not fixed by PR#4. PR#4 fixes install of node_exporter and PR#2 is about alert_manager.

**Comment by drewhemm** [comment]
When will this PR be accepted? We have had to fork this repo until the bug is fixed...

**Comment by brutus333** [comment]
I will fixed it right away. I added some version check. For alert_manager v0.1.0 the configuration was right.

**Comment by brutus333** [comment]
Sorry for not using your PR, I had to add version check.

**Pull request closed without merging**
