### PR TITLE
older versions of puppet don't know about the --to_yaml option

### LINKED ISSUE #118: Error: Could not parse application options: invalid option: --to_yaml
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby:2.1.5p273
- Distribution: Debian
- Module version: since #101.

## How to reproduce (e.g Puppet code you use)

Use older Puppet agent (we use Puppet master 4.8.2).

## What are you seeing
```
[...]
Info: Loading facts
Error: Could not parse application options: invalid option: --to_yaml
Could not retrieve fact='prometheus_alert_manager_running', resolution='<anonymous>': undefined method `[]' for false:FalseClass
Info: Caching catalog for mynode
[...]
```

## What behaviour did you expect instead

No warning

### PR DESCRIPTION
**Pull request by tuxmea**
switching back to scanning the result

fixes #118

### CODE REVIEW

**Comment by sathieu** [comment]
Thanks for this PR.

I have another error:
```
Error: Could not run: Could not find init script for 'alert_manager'
```

**Comment by tuxmea** [comment]
@sathieu next version with error handling. I am curious where the error is happening and whether the begin rescue block is helpful here.

**Comment by sathieu** [comment]
The rescue is not called because the error is in the puppet call.

This works:
``` ruby
Facter.add('prometheus_alert_manager_running') do
  setcode do
    Facter::Core::Execution.execute('puppet resource service alert_manager 2>&1').scan('running')[0]
  end
end
```

**Comment by bastelfreak** [comment]
Thanks for the PR!

**Pull request merged**
