### PR TITLE
add option to enable tracing in Prometheus config

### PR DESCRIPTION
**Pull request by fbegyn**
#### Pull Request (PR) description

Prometheus has support for tracing in the configuration file. This commit enables adding a tracing config to the config file.

source: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tracing_config

#### This Pull Request (PR) fixes the following issues

none

### CODE REVIEW

**Comment by roidelapluie** [comment]
REFERENCE.md is outdated

**Comment by fbegyn** [comment]
I'm afraid I'm too unfamiliar with the testing suite (and maybe this project as a whole), to really see what's going wrong in that Arch linux and Debian 12 test.

All help is welcome!

**Comment by roidelapluie** [comment]
Also happens on the main branch, so let's go ahead.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
