### PR TITLE
add varnish_exporter

### PR DESCRIPTION
**Pull request by blupman**
I have used haproxy_exporter and rabbitmq_exporter to create varnish_exporter,

it installs https://github.com/jonnenauha/prometheus_varnish_exporter/ which seems to be a commonly used varnish_exporter

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @blupman, thanks for your PR. Can you please check the used email address in your commit? It isn't associated with your github account.

**Comment by bastelfreak** [comment]
Please also rebase against our latest master branch. https://github.com/voxpupuli/puppet-prometheus/pull/172 introduced some conflicts.

**Comment by blupman** [comment]
Hi @bastelfreak 

Thanks for your feedback!, I have added my work email to the profile, also rebased, i took a few try's to figure out failing spectest on arch linux.

**Comment by blupman** [comment]
Hi @bastelfreak 

I have updated varnish_exporter to reflect the recent changes done to the master branch.

**Comment by bastelfreak** [comment]
thanks @blupman !

**Pull request merged**
