### PR TITLE
Feature/alerts prometheus2

### PR DESCRIPTION
**Pull request by jhooyberghs**
This PR adds alerts to prometheus 2.0 . I wrote this code because I ran into the same problem as issue #120 

This code should be backwards compatible, leaving all < 2.0 installations with the old epp template, and all newer prometheus installations can now use a yaml configuration hash, which gets converted to a YAML configuration file as needed according to the documentation (https://prometheus.io/docs/prometheus/2.0/migration/#recording-rules-and-alerts)

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @jhooyberghs, thanks for the PR. Are you able to add an acceptance test that installs prometheus 2 with the new hash?

**Comment by vStone** [comment]
@bastelfreak: Since the acceptance tests are minimal in general, I've just added spec tests.

**Comment by jhooyberghs** [comment]
@bastelfreak are these spec tests sufficient?

**Comment by bastelfreak** [comment]
Thanks for the PR @jhooyberghs !

**Pull request merged**
