### PR TITLE
Add parameter user / group for ressource archive

### LINKED ISSUE #448: /opt/prometheus user and group id is 3434. Should be managable.
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.14
- Ruby: 2.5.1
- Distribution: redhat and centos
- Module version: 8.4.0

## How to reproduce (e.g Puppet code you use)
Install the prometheus server

## What are you seeing
The /opt/prometheus-version... directory has user and group 3434
Is done for a reason?

## What behaviour did you expect instead
That the archive command in the install class has the option to set a user and group so it isn't randomly 3434.

### PR DESCRIPTION
**Pull request by dhoppe**
Fixes #448

### CODE REVIEW

**Comment by bastelfreak** [comment]
rebased the commit

**Comment by bastelfreak** [comment]
rebased

**Comment by ndelic0** [comment]
Is there any way to push for this PR?

**Comment by bastelfreak** [comment]
@ndelic0 I rebased it again.In case the acceptance tests fail again it would be nice if someone could investigate why they fail.

**Comment by ikonia** [comment]
these checks appear to be passing the failing tests are initial connection tests failing on the host running the test ? or are there other tests failing that I can't see ?

I'm happy to work through the failures to get this merged and released as it's a good fix for a frustrating bug.

**Review by igalic — CHANGES_REQUESTED** [review]
why not extend the existing tests to cover this behaviour change?

**Comment by TheMeier** [comment]
Closing due to inactivity. @dhoppe feel free to re-open

**Pull request closed without merging**
