### PR TITLE
release 3.1.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by alexjfisher — CHANGES_REQUESTED** [review]
Acceptance test failures suggest there really is a problem.  I think holding off pushing a new release until the issue is resolved or at least understood is best.

**Comment by bastelfreak** [comment]
@tuxmea I won't have time to look into this in the next days. You think you've any chance to do it?

**Comment by tuxmea** [comment]
I first have to implement the postgres_exporter (work paid by customer) - then I can look into failing tests.

**Comment by tuxmea** [comment]
I am able to reproduce the rror running the travis tests locally: `rvm use 2.4.2` `bundle install --path vendor` and then: `PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 bundle exec rake beaker`

Test were OK on first run and produced the service prometheus starting on the second run.

**Review by juniorsysadmin — APPROVED** [review]

**Comment by bastelfreak** [comment]
Addressed concerns from @alexjfisher

**Pull request merged**
