### PR TITLE
Add service restart on package change

### PR DESCRIPTION
**Pull request by rwaffen**
Add service restart on package change

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @rwaffen, thanks for the PR. Can you add an acceptance test for this? Maybe someting that installs the package, upgrades it and checks that the new version is running?

**Comment by rwaffen** [comment]
I'm not sure. I didn't do any acceptance test until now in puppet 🤔

**Comment by bastelfreak** [comment]
I did some tests locally. It's a bit ugly to write a test for this because we would need to get a package update which would trigger this. I checked the dependencies and the change looks fine.

**Comment by rwaffen** [comment]
yeah, was thinking about that, how to get an update. many thanks for the testing and merging 👍 .

**Pull request merged**
