### PR TITLE
puppetlabs/stdlib: Require 9.x

### PR DESCRIPTION
**Pull request by hashworks**

### CODE REVIEW

**Comment by marszip** [comment]
There is also a legacy function still in the config.pp:

```
  errors:
    Evaluation Error: Unknown function: 'has_key'.
      file: modules/prometheus/manifests/config.pp
      line: 262
      column: 9
      factsets: RHEL8
```

**Comment by smortex** [comment]
@hashworks do you want to rebase this on top of #668 and address the issue raised by @marszip?  This should fix CI :-)

**Comment by smortex** [comment]
The `validate_*` functions where made useless with datatypes introduced with Puppet 4. `$foo =~ Boolean` can be used when the datatype cannot be enforced directly at class parameters.

The dependency on postfix should be fixed by this PR when a new release include it:
https://github.com/voxpupuli/puppet-postfix/pull/357

**Comment by bastelfreak** [comment]
also contains https://github.com/voxpupuli/puppet-prometheus/pull/670

**Comment by bastelfreak** [comment]
released https://github.com/voxpupuli/puppet-postfix/pull/359

**Comment by bastelfreak** [comment]
needs a new release for https://forge.puppet.com/modules/saz/sudo : https://github.com/saz/puppet-sudo/pull/294

**Review by rwaffen — COMMENTED** [review]
LGTM

**Pull request merged**
