### PR TITLE
WIP: make managing of service files a parameter

### LINKED ISSUE #62: Prometheus service wont run if installed from package
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.6
- Ruby: puppets very own ruby
- Distribution: Debian Jessie
- Module version: from master

## How to reproduce (e.g Puppet code you use)

```
 class { 'prometheus':                                                                                                                                                                                        
         install_method => 'package', 
         ...
```

## What behaviour did you expect instead
If is "package" installation chosen, should be also used systemd service distributed with package.

## Any additional information you'd like to impart

If 'package' method is chosen, module still using own service which make prometheus not run. And without modules own service 'prometheus.yam' is not loaded because default is 'prometheus.yml'. So, i'm missing something or is this not supported use case? Thanks!

### PR DESCRIPTION
**Pull request by tuxmea**
fixes #62

### CODE REVIEW

**Comment by jan-waechter** [comment]
This breaks compatibility for packages that do not include a service file, i.e. self-baked with fpm, where one wants to use the service file provided by the prometheus module.

**Comment by tuxmea** [comment]
I am going to push an update soon

**Comment by bastelfreak** [comment]
I ma not sure if this approach is a good idea. Shouldn't our service files instead work with all installation methods? This is what we usually do in other modules. I would be okay with a generic $manage_service_files param or similar, where somebody can enble/disable the management.

**Comment by tuxmea** [comment]
As we can not say for sure how someone generates the package (/opt/prometheus/bin/prometheus or /usr/bin/prometheus) we should add a parameter to disable management of service files.

**Comment by bastelfreak** [comment]
Hi @tuxmea, are you still interested in this PR, or should I close this?

**Comment by bastelfreak** [comment]
I think we can close this, since we now have a `manage_service` param.

**Pull request closed without merging**
