### PR TITLE
Remove Future Code

### PR DESCRIPTION
**Pull request by lswith**
I would like to make the alert.pp file backwards compatible. This means that it can run without a dependency on the future parser.

I think making this codebase Puppet 4 compatible should require a completely new branch rather than one or 2 files that need future parser to be enabled.

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
According to policy, the way to maintain Puppet 3 compatibility is in a puppet3 branch. This has just recently been created. Reopen this against that branch, for further discussion. Thanks!

See:
https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/
https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/

**Comment by lswith** [comment]
this was against that branch!

**Comment by bastelfreak** [comment]
oh sorry! We're not used to have multiple branches, so most of us don't check the branch. We got a few PRs against master in the past days that  tried to drop puppet4 only code. Sorry!

**Comment by lswith** [comment]
thanks bud

**Comment by juniorsysadmin** [comment]
Oh that was embarrassing

**Pull request merged**
