### PR TITLE
Add support for the aarch64 architecture

### PR DESCRIPTION
**Pull request by ralimi**
#### Pull Request (PR) description

Add support for the aarch64 architecture

#### This Pull Request (PR) fixes the following issues

n/a

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @ralimi, thanks for the PR. Do you have an aarch64 platform by hand and could provide facts to https://github.com/camptocamp/facterdb ? Or as an alternative, could you mock this architecture in our current tests so we can ensure that everything still compiles?

**Comment by ralimi** [comment]
Thanks for the quick feedback!

I looked briefly at contributing to facterdb and, if I understand correctly, the way to get things included as part of the standard release is to have a vagrant box.  From https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=arm64 (I did an equivalent search for aarch64 too), it doesn't seem like there is an appealing/regularly-maintained option.  Let me know if I'm misunderstanding things there.

I'll dig around the unit tests to see where best to mock this.  A quick search (e.g., for armv7l) didn't yield examples. Let me know if I'm missing something there.

**Comment by bastelfreak** [comment]
you can have a look at https://github.com/camptocamp/facterdb/blob/master/facts/get_facts.sh. It's basically enough to run `facter -j` and put the output into a file. That's also the way I used to get the archlinux facts that are in facterdb.

**Comment by ralimi** [comment]
Hi @bastelfreak, what are the next steps here?

So far:
- I've got this running successfully in my local setup.
- Facts have be added to facterdb.

If I understand correctly, this wouldn't be used in tests until the next facterdb release.  If that understanding is correct, what is the best thing to do before then?

**Comment by bastelfreak** [comment]
Thanks for the work!

**Pull request merged**
