### PR TITLE
postfix exporter support

### PR DESCRIPTION
**Pull request by anarcat**
This provides support in the Puppet module for the [Postfix exporter](https://github.com/kumina/postfix_exporter). It is a fairly trivial patch, based on the `apache_exporter` class with small changes. 

It does follow the work in #303 to make it work with the Debian package. Note how it uses `env_vars` to pass the parameters to the `.service` file: this is a consequence of #303 *not* overriding the `.service` file when using the Debian package, and might *not* work if the `.service` file *is* overriden.

### CODE REVIEW

**Comment by anarcat** [comment]
ping! i believe this can be merged: it passes tests and doesn't *actually* require #303...

it would be quite motivating for me to continue working on this module if i could get trivial stuff like this merged in. :)

**Comment by dhoppe** [comment]
Please provide also tests like: 
* https://github.com/voxpupuli/puppet-prometheus/blob/master/spec/classes/apache_exporter_spec.rb

**Comment by dhoppe** [comment]
@anarcat The current tests are not failing, because we do not have any tests for the new exporter. Please add the missing tests and we are able to merge this pull requests.

**Comment by anarcat** [comment]
like in the bind exporter (#312), i've removed the debian-specific stuff from the YAML config, which belongs to the debian package (#303). To get it working right with the debian setup, the following is required:

```
prometheus::postfix_exporter::package_name: 'prometheus-postfix-exporter'
prometheus::postfix_exporter::service_name: 'prometheus-postfix-exporter'
prometheus::postfix_exporter::user: 'prometheus'
prometheus::postfix_exporter::group: 'prometheus'
```

**Comment by bastelfreak** [comment]
@anarcat can you please rebase and add a test for this?

**Comment by anarcat** [comment]
superseded by #396 thanks @alexjfisher !!!

**Pull request closed without merging**
