### PR TITLE
WIP: data/Debian.yaml, add package- and service-names for Debian-based prometheus-packages

### PR DESCRIPTION
**Pull request by unki**
Together with #430 this PR adapts the Debian-defaults regarding package- and service-names like they are actually present in Debian. _e.g._ all exporters are prefixed with `prometheus-`.

https://packages.debian.org/search?keywords=prometheus&searchon=names&suite=stable&section=all

```bash
user@host:~$ for A in $(apt-cache search ^prometheus- | awk '{ print $1 }' | xargs); do apt-file show $A 2>&1 | grep -E '(systemd/system)'; done
prometheus-alertmanager: /lib/systemd/system/prometheus-alertmanager.service
prometheus-apache-exporter: /lib/systemd/system/prometheus-apache-exporter.service
prometheus-bind-exporter: /lib/systemd/system/prometheus-bind-exporter.service
prometheus-bird-exporter: /lib/systemd/system/prometheus-bird-exporter.service
prometheus-blackbox-exporter: /lib/systemd/system/prometheus-blackbox-exporter.service
prometheus-haproxy-exporter: /lib/systemd/system/prometheus-haproxy-exporter.service
prometheus-mongodb-exporter: /lib/systemd/system/prometheus-mongodb-exporter.service
prometheus-mysqld-exporter: /lib/systemd/system/prometheus-mysqld-exporter.service
prometheus-nginx-exporter: /lib/systemd/system/prometheus-nginx-exporter.service
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-apt.service
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-apt.timer
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-ipmitool-sensor.service
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-ipmitool-sensor.timer
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-mellanox-hca-temp.service
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-mellanox-hca-temp.timer
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-smartmon.service
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter-smartmon.timer
prometheus-node-exporter: /lib/systemd/system/prometheus-node-exporter.service
prometheus-pgbouncer-exporter: /lib/systemd/system/prometheus-pgbouncer-exporter.service
prometheus-postgres-exporter: /lib/systemd/system/prometheus-postgres-exporter.service
prometheus-process-exporter: /lib/systemd/system/prometheus-process-exporter.service
prometheus-pushgateway: /lib/systemd/system/prometheus-pushgateway.service
prometheus-snmp-exporter: /lib/systemd/system/prometheus-snmp-exporter.service
prometheus-sql-exporter: /lib/systemd/system/prometheus-sql-exporter.service
prometheus-squid-exporter: /lib/systemd/system/prometheus-squid-exporter.service
prometheus-varnish-exporter: /lib/systemd/system/prometheus-varnish-exporter.service
prometheus-xmpp-alerts: /lib/systemd/system/prometheus-xmpp-alerts.service

```

### CODE REVIEW

**Comment by bastelfreak** [comment]
@unki can you take a look at the failing tests?

**Comment by unki** [comment]
> @unki can you take a look at the failing tests?

Need your advice here.

The situation is  - even before my #430 - that a lot of exporters are using `$service_name` for things like naming the installation-directory. _e.g._ see `redis_exporter.pp:L107`.

When the `$service_name`s for Debian are now referring their actual service-names on Debian - a init.d or systemd.service, like _e.g._ `prometheus-redis-exporter` - all the tests here are failing because they have the ordinary exporter-names like `redis_exporter` hardcoded.

Shall I...
- ... change the exporters to use `$package_name` instead of `$service_name` and pin the tests to the upstream exporter-names (`redis_exporter`)?
- ... change the tests to test a package-based installation on Debian instead of the download-url variant?

**Comment by anarcat** [comment]
> ... change the tests to test a package-based installation on Debian instead of the download-url variant?

i think that would be the way to go. if i remember correctly, that's how Arch does it.

and thanks for tackling this! i've got profiles here to work around this problem, would be great to get rid of them.

**Comment by bastelfreak** [comment]
In general I think we should always rely on packages if some are available. Arch Linux packages a few exporters and I implemented that in this module as well.

**Comment by TheMeier** [comment]
@unki is still relevant?

**Comment by TheMeier** [comment]
I will close this due to inactivity, please feel free to re-open if you still want to work on this

**Pull request closed without merging**
