### PR TITLE
Add CentOS 8 & RHEL 8 support

### PR DESCRIPTION
**Pull request by der-eismann**
#### Pull Request (PR) description
This PR adds support for CentOS 8 & RHEL 8. Basically I adapted earlier PRs for Debian 9 & Ubuntu 18.04.
Probably need to wait a while until `puppet/archive`, `puppetlabs/stdlib` and `camptocamp/systemd` also support these OS.

#### This Pull Request (PR) fixes the following issues
None

### CODE REVIEW

**Comment by bastelfreak** [comment]
Thanks for the PR @der-eismann. let's hope that Puppet Inc soon adds support to beaker so the tests will succeed.

**Comment by der-eismann** [comment]
Yeah... I was naive enough to believe they all work already with RHEL 8 which has been out for 4 months, but apparently it's not widely used in the puppet community. So I guess we will just have to wait a bit.

**Comment by der-eismann** [comment]
@bastelfreak Do you know where [this line](https://travis-ci.org/voxpupuli/puppet-prometheus/jobs/598046913#L1030) is coming from?
```
{"stream":"Step 4/15 : RUN yum install -y sudo openssh-server openssh-clients curl ntpdate"}
```
There is no ntpdate in CentOS 8, however I couldn't find it in `beaker-rspec`, `beaker-hostgenerator` or this repo.

//Edit: I think it's coming from beaker... They [fixed it](https://github.com/puppetlabs/beaker/commit/287e84c4fb287f9fafdf1eda79e140cf6e59fd94) for RHEL 8, but not for CentOS yet.

**Comment by bastelfreak** [comment]
@der-eismann I did a new  `puppet/archive` release which now supports CentOS 8.

**Comment by der-eismann** [comment]
Thanks! Should I do anything else, like adjust some dependencies? It's my first contribution in the puppet universe.
I'm also not sure why the tests are still failing.. [this guy](https://tickets.puppetlabs.com/browse/BKR-1613) says testing works, I hope this will be fixed soon. Need to get my upgrades done :smile:

**Pull request closed without merging**
