### PR TITLE
adding remote_write support

### PR DESCRIPTION
**Pull request by gangsta**
Hi,

Adding remote_write support for prometheus 2.X
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cremote_write%3E

BR
Karen

### CODE REVIEW

**Comment by tuxmea** [comment]
Looks good to me. Can you add spec tests for the new parameter?

**Comment by gangsta** [comment]
Hi @tuxmea ,

Isn't it defined [here](https://github.com/voxpupuli/puppet-prometheus/blob/master/spec/classes/prometheus_spec.rb#L173) ?
And in pull request [here](https://github.com/voxpupuli/puppet-prometheus/pull/144/files#diff-24bd423a6f866cf962eaf79b6a8bf255R22)

BR
Karen

**Comment by tuxmea** [comment]
Yes. But I am missing a test for the parameter, like: https://github.com/voxpupuli/puppet-prometheus/blob/master/spec/classes/prometheus_spec.rb#L203

**Comment by gangsta** [comment]
Here I need some help , Cause read parameter is also missing tests, maybe someone can help me to write this tests?

**Comment by tuxmea** [comment]
Busy today. I can provide a test within tomorrow.

**Comment by gangsta** [comment]
Thank you !

**Comment by gangsta** [comment]
Hi @tuxmea , 

Adding Readme support for Prometheus 2.0.0 see   https://github.com/voxpupuli/puppet-prometheus/issues/143

**Comment by gangsta** [comment]
Another pull is included , support for alertmanager 0.13.0 see https://github.com/prometheus/alertmanager/releases/tag/v0.13.0

**Comment by tuxmea** [comment]
Thanks. In future: Please keep separate issues in separate PR.

**Comment by tuxmea** [comment]
@kalinux  please find the following patch for spec:
```
diff --git a/spec/classes/prometheus_spec.rb b/spec/classes/prometheus_spec.rb
index 263d0e8..2590c21 100644
--- a/spec/classes/prometheus_spec.rb
+++ b/spec/classes/prometheus_spec.rb
@@ -253,6 +253,40 @@ describe 'prometheus' do
           end
         end
       end
+
+      context 'with remote write configured' do
+        [
+          {
+            version: '2.0.0-rc.1',
+            remote_write_configs: [
+              'url' => 'http://domain.tld/path',
+            ]
+          }
+        ].each do |parameters|
+          context "with prometheus version #{parameters[:version]}" do
+            let(:params) do
+              parameters
+            end
+
+            prom_version = parameters[:version] || '1.5.2'
+            prom_major = prom_version[0]
+
+            it {
+              is_expected.to compile
+            }
+            it {
+              is_expected.to contain_file('prometheus.yaml').with(
+                'ensure'  => 'present',
+                'path'    => '/etc/prometheus/prometheus.yaml',
+                'owner'   => 'prometheus',
+                'group'   => 'prometheus',
+                'content' => /http:\/\/domain.tld\/path/
+              )
+            }
+          end
+        end
+      end
     end
   end
 end
+
```

**Comment by gangsta** [comment]
Hi @tuxmea ,

Please review code.

BR
Karen

**Comment by tuxmea** [comment]
Thank you.
Some rubocop tests fail:
```
spec/classes/prometheus_spec.rb:262:48: C: Style/TrailingCommaInLiteral: Avoid comma after the last item of an array. (https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas)
              'url' => 'http://domain.tld/path',
                                               ^
spec/classes/prometheus_spec.rb:272:13: W: Lint/UselessAssignment: Useless assignment to variable - prom_major. (https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars)
            prom_major = prom_version[0]
            ^^^^^^^^^^
spec/classes/prometheus_spec.rb:283:30: C: Style/RegexpLiteral: Use %r around regular expression. (https://github.com/bbatsov/ruby-style-guide#percent-r)
                'content' => /http:\/\/domain.tld\/path/
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by gangsta** [comment]
So how is this can be solved ? 🤔

**Comment by tuxmea** [comment]
@kalinux 
in spec/classes/prometheus_spec.rb:
remove line  272 - here you specify a variable which you don't use
in line 262 remove the trailing comma
in line 283: use %r{http:\/\/domain.tld\/path}

Try to run check tests prior pushing your changes. For workstation setup you can read on [example42 blog developer setup](https://www.example42.com/2017/06/26/psick-developer-environment-setup/) and have a look at the puppet code development and testing section in the [example42 blog summary](https://www.example42.com/2018/01/01/2017_categorized_posting_summary/)

**Comment by gangsta** [comment]
Hi @tuxmea ,

yeah! we did it, all checks are passed and my master branch is used by me in production so Prometheus 2.0.0 is working very well ! I thinks we are ready to merge branch . Thanks for awesome collaboration.

**Comment by tuxmea** [comment]
looks good to me. @bastelfreak any comments from your side?

**Comment by gangsta** [comment]
hi @tuxmea ,

I'll say `Silence is a sign of acceptance` from @bastelfreak . (ps I don't know the origin of “Silence is a sign of acceptance”)

Regards

**Comment by tuxmea** [comment]
;-) merging now.

**Pull request merged**
