### PR TITLE
Ruby 1.8 compatibility (Agent-side)

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by tuxmea** [comment]
Ruby 1.8? Are you still running on Puppet 2.x?

**Comment by alexjfisher** [comment]
@tuxmea Puppet 3 on RedHat/CentOS 6 systems were usually ruby 1.8.

But we don't support puppet 3 at all anymore, (since the begginning of last year IIRC), and dropped support for ruby 1.8 maybe a year before that.

**Comment by tuxmea** [comment]
@sathieu please read comment from @alexjfisher. voxpupuli skipped puppet 3 and ruby 1.8 support. consider upgrading to puppet 4 or 5.
Please reopen in case that you see an urgent need for ruby 1.8 support.

**Comment by sathieu** [comment]
@tuxmea @alexjfisher Yes please reopen this PR. It is just a one line patch which fixes errors on our old servers (we have a dozen of those oldies, and yes upgrade is planned).

**Comment by tuxmea** [comment]
@sathieu reopened. can anybody else place his vote on this PR?
Looks good to me.

**Comment by alexjfisher** [comment]
Because this is just a change to a fact and facts run on all hosts, I'm ok with this.
But... this wouldn't mean we support *using* the prometheus module on ruby 1.8 or puppet 3 systems.

**Comment by sathieu** [comment]
Thanks !

**Pull request merged**
