### PR TITLE
mongodb_exporter: Add acceptance tests

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by othalla — APPROVED** [review]

**Comment by alexjfisher** [comment]
Related to https://github.com/voxpupuli/puppet-prometheus/issues/366

**Comment by olivierHa** [comment]
Hello, 

What about this PR ? 
mongodb exporter version is now "0.11.0" and is still being extracted to /opt directly.

Applying the same modification as the postgresql exporter is working (c

Do you want a PR with those modification (copypasting ?)

Regards

**Comment by bastelfreak** [comment]
Hi @olivierHa, a PR if an acceptance test would be most welcome!

**Comment by kuldazbraslav** [comment]
@bastelfreak mongodb_exporter needs to connect to a mongo instance when it starts up. I used simple mongo in docker when I tested it, is it possible to use in the acceptance test too?

**Pull request closed without merging**
